### ISSUE TITLE
Unable to upload on a mac

### ISSUE THREAD

**Issue by jchonig** [mcci-catena/Arduino_Core_STM32#176]
Arduino: 1.8.13 (Mac OS X), Board: "MCCI Catena 4618, DFU (include bootloader), USB Serial, 32 MHz (most power), MCCI Trusted Boot, Smallest (-Os default), North America 915 MHz, The Things Network, Default, works everywhere"

Sketch uses 86304 bytes (50%) of program storage space. Maximum is 172032 bytes.
Global variables use 8984 bytes (43%) of dynamic memory, leaving 11496 bytes for local variables. Maximum is 20480 bytes.
dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Opening DFU capable USB device...
ID 0483:df11
Run-time device DFU version 011a
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
dfu-util: Invalid DFU suffix signature
dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
dfu-util: Non-valid multiplier 'g', interpreted as type identifier instead
Determining device status: state = dfuERROR, status = 10
dfuERROR, clearing status
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 011a
Device returned transfer size 2048
DfuSe interface name: "Internal Flash  "
Downloading to address = 0x08000000, size = 10768
Download	[=========================] 100%        10768 bytes
Download done.
File downloaded successfully
dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Match vendor ID from file: 040e
Opening DFU capable USB device...
ID 0483:df11
Run-time device DFU version 011a
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
dfu-util: Error: File ID 040e:00d1 does not match device (040e:df11 or 0483:df11)
dfu-util: Error: File ID 040e:00d1 does not match device (040e:df11 or 0483:df11)

Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 011a
Device returned transfer size 2048
main upload failed

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by terrillmoore** [comment]
Typo in updated script - missing $ in front of variable substitution here:
https://github.com/mcci-catena/Arduino_Core_STM32/blob/659445b3b1fa17a7511c26854fd6216cefebeb21/tools/macosx/stm32l0-upload#L116
and here:
https://github.com/mcci-catena/Arduino_Core_STM32/blob/659445b3b1fa17a7511c26854fd6216cefebeb21/tools/macosx/stm32l0-upload#L122

Put `$` in front of `VIDPID`.
