### ISSUE TITLE
version 1.08 not installed from board manager

### ISSUE THREAD

**Issue by DavidBoelee** [mcci-catena/Arduino_Core_STM32#18]
When installing this repo from the board manager, version 1.07 is installed, and not 1.08.

**Comment by terrillmoore** [comment]
@sjpark-mcci -- please try to duplicate this today, and ask David follow-up questions as needed.

**Comment by sjpark-mcci** [comment]
That was because version 1.0.8 was not updated yet. It is now updated. Please try and let me know if you are still having the issue. Sorry for the delay.

**Comment by DavidBoelee** [comment]
That worked. Thanks for adressing this issue!

**Comment by terrillmoore** [comment]
Thanks for reporting it.
