### ISSUE TITLE
Clarify use of USB and regular serial ports

### ISSUE THREAD

**Issue by terrillmoore** [mcci-catena/Arduino_Core_STM32#29]
In v1.1.0 and earlier, if you download a test sketch and use DFU to upload it, you may or may not get serial output.

- if you have set "Serial ports: No serial", then serial output will appear on USB.
- if you have set "Serial Ports: (any other value)", then no output will appear on USB.

This is confusing to people used to the Feather M0. It happens because Serial points to the UART if available. For people unfamiliar with the board and the settings, it makes them think that the board is not working.

We should change the rules to match the Feather M0. Serial should point to UsbSerial if available, and to the first UART otherwise.

**Comment by chwon64** [comment]
I think we need to remove "USB interface" menu and add "USB serial" in the "Serial interface" menu.

So "Serial interface" menu has submenu as below:
1. USB Serial (default)
2. Generic Serial

**Comment by terrillmoore** [comment]
Closed by #44
