### ISSUE TITLE
Add system clock setting menu

### ISSUE THREAD

**Issue by chwon64** [mcci-catena/Arduino_Core_STM32#43]
We need to add system clock setting menu. It is very useful to reduce power consumption. 
New menu is "System clock" and it has submenu as below:
1. HSI 16 MHz (default)
2. PLLCLK 24 MHz
3. PLLCLK 32 MHz
4. MSI 2097 KHz (no USB Serial)
5. MSI 4194 KHz (no USB Serial)

**Comment by terrillmoore** [comment]
Closed by #44
