### ISSUE TITLE
Catena 4801 BSP is not correct or consistent with others

### ISSUE THREAD

**Issue by terrillmoore** [mcci-catena/Arduino_Core_STM32#50]
When the Catena 4801 was added, the templating system was broken.

- boards.json is not syntactically correct -- when `boards.json` was modified, nobody ran the script.
- the template generation system was not used to update boards.txt -- if it had been, the generated boards.txt would be lacking the 4801 section (because of the error).
- material was added to boards.txt that is not compatible with the templating system. 

The instructions in "MCCI-ADDING-BOARDS.md" are very clear. Let's follow them in the future.

A new BSP should have been created for the 4801 rather than trying to wedge it into the existing BSP; or the templating mechanism should have been extended.

**Comment by dhineshkumarmcci** [comment]
Thank you for the feedback Terry.

Will be making sure, the instructions in "MCCI-ADDING-BOARDS.md" is followed perfectly in future.

The updated 'boards.txt' has been tested with the MCCI Catena 4801.
