### ISSUE TITLE
Pullup in peripheral pins seems to be wrong

### ISSUE THREAD

**Issue by dhineshkumarmcci** [mcci-catena/Arduino_Core_STM32#66]
Pullup configuration for SPI pins and USART pins seems to be wrong in "PeripheralPins.c" for 4801. They should be configured as No_Pullup. #41

**Comment by terrillmoore** [comment]
@dhineshkumarmcci can you modify on your side and test? I'm not sure ChaeHee is set up with a 4801 yet. Then you can submit a pull request. Thanks!

**Comment by dhineshkumarmcci** [comment]
We have tested it in our end and that resulted in fall of power consumption by 210 uA.

- With Pullups - 263 uA
- With No_Pullups - 53 uA

**Comment by terrillmoore** [comment]
That's great. So my suggestion is that you submit a pull request.... that way it's easy to review and we can just accept the change and move forward. In the pull request, please include the text "Fix #66:".....
