### ISSUE TITLE
STM32 Low power consumption with Standby mode

### ISSUE THREAD

**Issue by dhineshkumarmcci** [mcci-catena/Arduino_Core_STM32#73]
In Standby mode, on enabling the Power interface clock, Low power voltage regulator, and Ultra-Low-power mode, power consumption can be reduced.

**Comment by terrillmoore** [comment]
This change is incorrect. The *caller* (according to docs) is responsible for doing the power management. I have reverted this change.

**Comment by terrillmoore** [comment]
In particular, there's a fundamental misunderstanding of how the WUF bit is supposed to be used.

You must (at the application level, or at least at a higher level than this)

1. clear the WUF *before* setting up the event sources.
2. set up the event sources (the RTC)
3. call `HAL_PWR_EnterSTANDBYMode()`.  

Then, in enter standby mode, if an event has occurred between 1 and 3, it wakes up immediately. If you clear WUF in`HAL_PWR_EnterSTANDBYMode()`, then you'll miss an event. This is forbidden design style according to MCCI rules; even if you don't think the event could possibly happen, we are required to code defensively.

I believe `HAL_PWR_EnterSTANDBYMode()` should clear the SBF. I've opened #80 for this.
