### ISSUE TITLE
Catena 4551 Continuous reset when USB enabled while running via Battery power

### ISSUE THREAD

**Issue by terrillmoore** [mcci-catena/Arduino_Core_STM32#9]
Cloned from https://github.com/mcci-catena/arduino-boards/issues/7

During uploading firmware, If USB interface -> "Enable USB device" option is selected. Then Catena 4551 radio resets continuously resetting while running in battery power. Same working fine with USB power.

Recommendation,
If want to run in battery power, During uploading firmware, In the tool setting select USB interface -> "None" and select serial interface -> "Generic serial"

**Comment by terrillmoore** [comment]
@svelmurugan92 do we still see this? If not, can we close this?

**Comment by svelmurugan92** [comment]
@terrillmoore  It's fixed we can close this issue
