### ISSUE TITLE
Remove the board build old flag in boards.json

### ISSUE THREAD

**Issue by dhineshkumarmcci** [mcci-catena/Arduino_Core_STM32#94]
As Catena 4630 is added after the implementation of new naming`(build.board=MCCI_{something})` methodology #49 , it do not require the backward compatibility. So I hope we can remove `build_board_old_flags` from **boards.json**.
https://github.com/mcci-catena/Arduino_Core_STM32/blob/9864576a4cc77b25efe446da907acd7ba5c5e793/boards.json#L54
@terrillmoore @chwon64 Is that ok to remove the `build_board_old_flags`?

**Comment by terrillmoore** [comment]
You can remove it for new boards. *But* -- we have to document this properly in the appropriate README.md (there's an update in #96, so I reckon we have some place to document this).

**Comment by dhineshkumarmcci** [comment]
Removed the `build_board_old_flags` and pushed to branch **issue95**. Added up with pull request #98
